parameters:
#    guilro_test.example.class: Guilro\TestBundle\Example

services:
#    guilro_test.example:
#        class: %guilro_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
