Guilro\CrudTestBundle\Entity\Tag:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
            nullable: true
    manyToOne:
        task:
            targetEntity: Task
            inversedBy: tags
            cascade: [ "persist" ]
            joinColumn:
                name: task_id
                referencedColumnName: id
