Guilro\CrudTestBundle\Entity\Task:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
    oneToMany:
        tags:
            targetEntity: Tag
            mappedBy: task
            cascade: [ "persist" ]
    lifecycleCallbacks: {  }
